version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
        MYSQL_DATABASE: ${MYSQL_DB}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
        - /var/lib/mysql:/var/lib/mysql
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./docker/conf/dev/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: bitnami/php-fpm:latest
    volumes:
      - .:/app
    links:
      - mysql
  redis:
    image: redis
