version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
        MYSQL_DATABASE: ${MYSQL_DB}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
        - /var/lib/mysql:/var/lib/mysql
  web:
    build: ./docker
    volumes:
      - .:/app
    ports:
      - '80:80'
    links:
      - mysql
  redis:
    image: redis
