version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_DATABASE: db
        MYSQL_USER: user
        MYSQL_PASSWORD: 123
    volumes:
        - /var/lib/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  web: 
    build: ./docker
    volumes:
      - .:/app
    ports:
      - '80:80'
    links:
      - mysql
  redis:
    image: redis
